"""Add device field

Revision ID: 0a060d566e9d
Revises: 37a3aad30da2
Create Date: 2026-01-12 18:13:16.461628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a060d566e9d'
down_revision = '37a3aad30da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amigos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amigos', schema=None) as batch_op:
        batch_op.drop_column('device')

    # ### end Alembic commands ###
